//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FabricStockOperation
    {
        public int Id { get; set; }
        public int FabricId { get; set; }
        public double Quantity { get; set; }
        public string Purpose { get; set; }
        public System.DateTime OperationDate { get; set; }
        public string OperationType { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int Status { get; set; }
    
        public virtual FabricDetail FabricDetail { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
    }
}
